print("A program to display the following table")
print("a",        "a^2",            "a^3")
print("1",         1 * 1,            1 * 1 * 1)
print("2",         2 * 2,            2 * 2 * 2)
print("3",         3 * 3,            3 * 3 * 3)
print("4",         4 * 4,            4 * 4 * 4)